### ISSUE TITLE
Parent Issue - Docs structure improvement

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz-web#160]
- [ ] https://github.com/SigNoz/signoz.io/issues/120
- [x] https://github.com/SigNoz/signoz.io/issues/119
- [ ] https://github.com/SigNoz/signoz.io/issues/122

Inspiration Posthog and Clickhouse docs
